name: riverpod_counter_app
description: Simple Flutter app. Use Riverpod to improve basic counter app.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.7
  intl: ^0.18.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

